version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - apt install -y zip
      - curl -LO https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      - unzip terraform_1.9.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - chmod +x /usr/local/bin/terraform
      - terraform --version
      - aws --version
      - aws configure set default.region $REGION
      - aws configure set default.aws_access_key_id $ACCESS_KEY
      - aws configure set default.aws_secret_access_key $SECRET_KEY
      - cat ~/.aws/credentials

  pre_build:
    commands:
      - echo "Changing to the specific directory"
      - cd vpc
      - echo "Initializing Terraform in $(pwd)"
      - terraform init
  build:
    commands:
      - echo "Applying Terraform"
      - terraform apply -auto-approve
